### ISSUE TITLE
Weird results, possible bug

### ISSUE THREAD

**Issue by gleporeNARA** [exponential-decay/signature-development-utility#14]
Created a signature per the attached screeshot, and got this XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<FFSignatureFile xmlns="http://www.nationalarchives.gov.uk/pronom/SignatureFile" Version="1" DateCreated="2020-09-28T13:35:02+00:00">
  <InternalSignatureCollection>
  <InternalSignature ID="1" Specificity="Specific">
  <ByteSequence Reference="BOFoffset">
    <SubSequence MinFragLength="0" Position="1" SubSeqMaxOffset="9" SubSeqMinOffset="9">
      <Sequence>464954</Sequence>
      <DefaultShift>4</DefaultShift>
      <Shift Byte="46">3</Shift>
      <Shift Byte="49">2</Shift>
      <Shift Byte="54">1</Shift>
    </SubSequence>
  </ByteSequence>
</InternalSignature>
</InternalSignatureCollection>
<FileFormatCollection>
  <FileFormat ID="1" Name="Garmin FIT Activity File" PUID="Gar/1" Version="1.0" MIMEType="fit">
    <InternalSignatureID>1</InternalSignatureID>
    <Extension>fit</Extension>
  </FileFormat>
</FileFormatCollection></FFSignatureFile>
```

The PUID and MIMEType seem off, with the PUID using part of the Name value and the MIMEType using the Extension.

Am I doing something wrong, or interpreting the results incorrectly?

![puid](https://user-images.githubusercontent.com/21240012/94439242-2bee4d00-016e-11eb-9ff4-b2b308561172.jpg)

**Comment by ross-spencer** [comment]
@gleporeNARA thank you so much for doing this testing today! That was an oversight on my part and I just happened to have a moment over breakfast to fix it. The commit is https://github.com/exponential-decay/signature-development-utility/commit/536763ebca0cd999ddc5015537f5a937e3af803d and should be deployed on the server for you already!

**Comment by gleporeNARA** [comment]
Looks good, thanks!
