### ISSUE TITLE
XML File Name

### ISSUE THREAD

**Issue by gleporeNARA** [exponential-decay/signature-development-utility#15]
Version 2 names the resulting XML file according to the signature dev value whereas version 1 used the Signature Name. I find Signature Name to be a better filename, since I never change the dev value (honestly, not sure if I should be or not...)  I end up with a lot of "development-signature-dev-1 (2).xml" files instead of the more readable "CMZ-Compressed-Archive-v1.0-signature-file.xml".

Just a thought.

**Comment by ross-spencer** [comment]
This was a nice easy one too - it's a great observation and also makes my job easier! I've now implemented: 

Standard signature: `{format-name}-{format-version}-signature-file.xml`
Container signature: `{format-description]-{format-puid}-{today's-date}.xml`

They seem to work nicely with DROID and yeah, might just create fewer of those `filename(x)` files which can get hard to manage. It's not yet perfect for container signatures, but maybe a tad better.

**Comment by gleporeNARA** [comment]
Tested, working, and closed! Thanks.
