### ISSUE TITLE
Signature Not Complete?

### ISSUE THREAD

**Issue by gleporeNARA** [exponential-decay/signature-development-utility#16]
Created two identical signatures, one with version 1 and one with version 2. The Version 1 signature correctly matches files, while the version 2 signature does not. The difference is:

Version 1 - "`<ByteSequence> <SubSequence MinFragLength="0" Position="1" SubSeqMinOffset="0">`"

Version 2 - "`<ByteSequence Reference=""> <SubSequence MinFragLength="0" Position="1" SubSeqMaxOffset="0" SubSeqMinOffset="0">`"

Full files:

Version 1:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<FFSignatureFile xmlns="http://www.nationalarchives.gov.uk/pronom/SignatureFile" Version="1" DateCreated="2020-09-28T15:05:37+01:00">
  <InternalSignatureCollection>
  <InternalSignature ID="1" Specificity="Specific">
  <ByteSequence>
    <SubSequence MinFragLength="0" Position="1" SubSeqMinOffset="0">
      <Sequence>576F6C6672616D204344462046696C65</Sequence>
      <DefaultShift>17</DefaultShift>
      <Shift Byte="57">16</Shift>
      <Shift Byte="6F">15</Shift>
      <Shift Byte="6C">2</Shift>
      <Shift Byte="66">13</Shift>
      <Shift Byte="72">12</Shift>
      <Shift Byte="61">11</Shift>
      <Shift Byte="6D">10</Shift>
      <Shift Byte="20">5</Shift>
      <Shift Byte="43">8</Shift>
      <Shift Byte="44">7</Shift>
      <Shift Byte="46">4</Shift>
      <Shift Byte="69">3</Shift>
      <Shift Byte="65">1</Shift>
    </SubSequence>
  </ByteSequence>
</InternalSignature>
</InternalSignatureCollection>
<FileFormatCollection>
  <FileFormat ID="1" Name="Computable Document Format" PUID="dev/1" Version="1.0" MIMEType="text/plain">
    <InternalSignatureID>1</InternalSignatureID>
    <Extension>cdf</Extension>
  </FileFormat>
</FileFormatCollection></FFSignatureFile>
```

Version 2: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<FFSignatureFile xmlns="http://www.nationalarchives.gov.uk/pronom/SignatureFile" Version="1" DateCreated="2020-09-28T14:06:23+00:00">
  <InternalSignatureCollection>
  <InternalSignature ID="1" Specificity="Specific">
  <ByteSequence Reference="">
    <SubSequence MinFragLength="0" Position="1" SubSeqMaxOffset="0" SubSeqMinOffset="0">
      <Sequence>576F6C6672616D204344462046696C65</Sequence>
      <DefaultShift>17</DefaultShift>
      <Shift Byte="57">16</Shift>
      <Shift Byte="6F">15</Shift>
      <Shift Byte="6C">2</Shift>
      <Shift Byte="66">13</Shift>
      <Shift Byte="72">12</Shift>
      <Shift Byte="61">11</Shift>
      <Shift Byte="6D">10</Shift>
      <Shift Byte="20">5</Shift>
      <Shift Byte="43">8</Shift>
      <Shift Byte="44">7</Shift>
      <Shift Byte="46">4</Shift>
      <Shift Byte="69">3</Shift>
      <Shift Byte="65">1</Shift>
    </SubSequence>
  </ByteSequence>
</InternalSignature>
</InternalSignatureCollection>
<FileFormatCollection>
  <FileFormat ID="1" Name="Computable Document Format" PUID="dev/1" Version="1.0" MIMEType="text/plain">
    <InternalSignatureID>1</InternalSignatureID>
    <Extension>cdf</Extension>
  </FileFormat>
</FileFormatCollection></FFSignatureFile>
```

SAMPLE FILES

[cdf.zip](https://github.com/exponential-decay/signature-development-utility/files/5292853/cdf.zip)

**Comment by ross-spencer** [comment]
Thanks Greg - this should be an easy-ish fix too - but I haven't an instinct what I'm missing like with  the other too. I'll take a look this evening. 

I just happened to have a spare moment this morning for the other two. Good luck with the rest of the testing today, and thanks heaps already!

**Comment by ross-spencer** [comment]
I think this will work now @gleporeNARA. I wasn't quite handling `Variable` sequences from the form fields in the same way but it looks like we've caught that. It's working in DROID:

![image](https://user-images.githubusercontent.com/1880412/94505738-c46de700-01d9-11eb-8ffe-884372fd57df.png)

I haven't figured out a good way to do integration testing but I have tried a couple of different combinations tonight and it looks like we should be making identical signatures to 1.0 again. 

The fix is in https://github.com/exponential-decay/signature-development-utility/commit/e5b11757ea71bdd8fcf7f9080ea932125aa475f4
