### ISSUE TITLE
Add Sequence Carries Over Offset

### ISSUE THREAD

**Issue by gleporeNARA** [exponential-decay/signature-development-utility#17]
Minor issue, when the initial sequence has an offset, the Add Sequence button carries over that offset, which probably should be reset to zero.

**Comment by ross-spencer** [comment]
Good call Greg. This was an indication of carrying over some detritus from my first method of cloning the UI components. This should be fixed with a bit of clean-up too in https://github.com/exponential-decay/signature-development-utility/commit/8d0fe614e8d65245cc8bf82ab44bd38bcc3a9b30now.

**Comment by gleporeNARA** [comment]
Looks good, closing.
