### ISSUE TITLE
Case Sensitive Container signatures

### ISSUE THREAD

**Issue by thorsted** [exponential-decay/signature-development-utility#22]
Many container signatures use ascii text for sequence strings and they are case sensitive. Current utility forces uppercase for all text.

**Comment by ross-spencer** [comment]
Related to https://github.com/exponential-decay/signature-development-utility/issues/9

**Comment by ross-spencer** [comment]
Thanks Tyler. Upper case restriction removed with https://github.com/exponential-decay/signature-development-utility/commit/66d3cd248f281abcb707197577679df50d8af8a5 there's definitely some more work to be done here around validation etc. I've linked a related issue. Hopefully this will do the trick for now. ffdev.info should be updated as well. Let me know!
